# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'NIT_08.12.2020' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RealmSwift'

  # Pods for NIT_08.12.2020

  target 'NIT_08.12.2020Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NIT_08.12.2020UITests' do
    # Pods for testing
  end

end
